#!/bin/bash
case $1 in
"usage")
	echo "$(basename $0) [BASENAME]"
	echo "  Open \$TODO_DIR/BASENAME.txt in \$EDITOR."
	echo "  If BASENAME is not given, defaults to 'todo'."
	;;
*)
	if [[ $2 != *[!0-9]* ]]; then
		#The variable is entirely numercal
		NUM=$2
		FILE=${3:-todo}.txt
	else
		#The variable is contains some non-numerical characters
		NUM=1
		FILE=${2:-todo}.txt
	fi

	if [ -n "$EDITOR" ]; then
	  vim +$NUM $TODO_DIR/$FILE
	else
		echo "Error: The EDITOR environment variable is not set"
	fi
	;;
esac
